variable "account_id" {}
variable "ami_name" {}
variable "source_instance_id" {}
variable "aws_region" {}
variable "destination" {}
variable "copyname" {}
variable "profile" {}
variable "name" {}
variable "aws_source_region" {}