#account_id         = "082547219836"
ami_name           = "wordpress_ami2"
source_instance_id = "i-0dae4c6b6fbedc7b3"
aws_region         = "us-west-2"
destination = "us-west-1"
copyname = "wordpress"
profile = "netfort"
aws_source_region = "us-west-2"